const getQuotes = new Object({
   madara: ["The concept of hope is nothing but rejection.  A word that has no true meaning", "The longer you live... the more you realize that reality is simply pain, suffering and emptiness", "When a person learns to love, he must bear the risk of hatred", "Nine-Tails, you  just a momentary life, but the temporary existence of a combined energy ... an energy that was once the only, final form!  An unstable force, devoid of reason or common sense, you need a guide to point you to the goal", "Balance is what moves the world", "Only people can think about the world, shedding blood", "People are nothing but  divided between the two sides of the coin.  They will want to fight for peace, but with a physical war, and only this victory will bring them final peace", "Hope is not where we cling to something, but that we let go of everything and keep an optimistic approach to  life", "The world is nothing but a game of balance.  There will always be something bad to balance the good", "In this world, wherever there is light, there are shadows.  As long as the concept of winners exists, there must be losers", "Love is the most important element, but not everyone gets it.  Not having love is normal, but to survive in this world, you need to make yourself capable and succeed", "People can not show each other their true feelings.  Fear, suspicion and resentment will never subside", "A man seeks peace, but at the same time yearns for war... These are two spheres that belong exclusively to a man.  Only people can think about the world by shedding blood.  They are two sides of the same coin… to protect something… you have to sacrifice another", "This world is filled with hatred, agony and suffering.  All this is the result of dishonesty and lies", "Life will always throw you new challenges just when you feel that you have succeeded but you have to hang on there, firmly, and get through it", "Things never go the way we are comfortable  , but go on their schedule", "Unstable force, devoid of intelligence or reason, you need a guide who will show you the goal", "Only those who are able to resist everything that comes their way without flinching, can survive even the most  cruel trials", "Our life is short and transient.  We don't have much time in this world.  But what really matters is how we use and spend the time we are given", "No matter how strong your opponent is, if you predict his moves, you can defeat him"],
   info: ({
   description: "Madara Uchiha (うちはマダラ, Madara Uchiha) was the legendary leader of the Uchiha clan. He founded the Hidden Leaf Village with his friend and rival, Hashirama Senju, with the intent of ushering in an era of peace. When the two parted ways,  How exactly to reach this world, they fought for dominance of the village in a battle that ended with Madara's death.However, he subsequently rewrote his death and began to hide from the world in order to continue working on his plans.As it turned out, Madara was not in  able to complete them during his natural life, so he entrusted his knowledge and aspirations to Obito Uchiha shortly before his real death.Years later, Madara was resurrected, but eventually met the final failure of his plans before dying again.",
   clan: "Uchiha",
   status: "Dead",
   date: "December 24",
   height: "Part II: 179 cm",
   weight: "Part II: 71.3 kg",
   element: "Fire, wind, lightning, water, earth, grass, storm, yin, yang, yin-yang",
   rank: "Renegade Ninja",
   family: "Tajima Uchiha (Father)\nIzuna Uchiha (Younger Brother)"
 })
 });

 module.exports = getQuotes;