const getQuotes = new Object({
   nagato: ["As long as humans exist, there will be hatred.  Real peace is impossible on this cursed earth", "Even just by living, we hurt others in an attempt to avoid suffering ourselves.  Our existence guarantees that hatred will never disappear.  Peace and harmony do not exist in this damned world", "If you know real pain, you won't confuse it with anything.  And even if you know another pain, you cannot understand the true one.  And it's true", "It's too late for me to believe Master Jiraiya's words!  The true world does not exist!  While we live in this damned land, there will be no peace!", "Love gives rise to suffering, gives rise to hatred and makes it possible to know pain.", "We live in the present, mourn the past and wonder about the future.  Such is the nature of history", "Our goals are very similar to you, we want to bring the world that our teacher so dreamed of, we do not differ from each other, because we act based only on a personal idea of justice.  The justice that I brought upon Konoha is no different from what you intend to do to me.  The pain of losing loved ones is the same for everyone.  You and I are two kindred spirits who have known this pain.  You for your justice, I for mine.  We are just two ordinary people pushed by a kind of revenge called justice.  However, calling revenge - justice, it will only bring more revenge in return, thus creating a vicious circle of hatred.  We live in the present, mourn the past and wonder about the future, such is the nature of history.  It is time to realize that people by their nature are not able to come to a general agreement.  This world lives only with hatred.", "People are not able to understand each other, hatred rules the world", "Love is suffering that generates hatred, which leads to severe pain.", "War brings only suffering, without giving happiness to anyone in return  , and the death of loved ones is the most terrible pain that can be endured.\n\nWithout exception, death brings nothing but pain, contributing to the birth of hatred.\n\nThe more senseless victims there are, the stronger the hatred and pain of heart wounds that will never  will drag on.\n\nSuch is the nature of war...", "Hatred is born from the desire to protect loved ones...", "We know what pain is, and we try to be kinder to others.\nPain helps us grow up faster, understand that  important for us.\nAfter all, only when we grow up do we begin to realize the cost of our actions.\nOnly those who know true pain can find the answer for themselves."],
   info: ({
   description: "Nagato (長門, Nagato Uzumaki) was a shinobi of the Hidden Rain Village and a descendant of the Uzumaki clan. Forming Akatsuki with his fellow war orphans, Nagato dreamed of bringing peace to the cruel shinobi world. However, after Yahiko's death, Nagato  adopted the alias Pain (ペイン, Pain) and partnered with Konan to become the leader of the new Akatsuki: Akatsuki, whose task it will be to forcibly bring peace to the earth by any means necessary.After his conversation with Naruto Uzumaki, Nagato realized his mistakes and sacrifices himself  , resurrecting the other shinobi of the Hidden Leaf Village.",
   clan: "Uzumaki",
   status: "Dead",
   date: "September 19",
   growth: "Part II: 175.5 cm",
   weight: "Part II: 40.1 kg",
   element: "Wind, water, earth, lightning, fire, yang",
   rank: "Rank-S",
   family: "Ise (Father)\nFuso (Mother)"
 })
 });

 module.exports = getQuotes;