const getQuotes = new Object({
   // from part of Yahiko
   paine: ["You can't appreciate the beauty of an entire forest from just one tree", "You can't understand the beauty of a forest by appreciating just one tree.  You simply are not able to realize the true meaning of the world", "Knowing the past, we can look into the future - this is how history teaches us.  From it we know that people will never be able to open their eyes and understand each other", "But if you justify revenge with words about justice, it will give rise to a new revenge.  It will give rise to a chain of hatred", "People are not able to understand each other, hatred rules the world", "You can consider my understanding of the world to be fundamentally wrong, but the idea that everyone can live with each other sounds much more absurd", "Enmity inevitably brings fear  and pain to both sides", "People.  The whole world knows what pain is.  And this fear will be the medicine that will stop the war.  This world has not yet reached a state of equilibrium, we can say that it is still growing.  Pain will make the world grow up, as it did me.  After all, our world is just a child", "Your so-called world is only cruelty for us", "People can hardly turn their tongues to call wise creatures.  You won't expect peace from them otherwise.  Years will pass and this pain will begin to subside, its power will begin to weaken and people will plunge into the abyss of endless wars, and then they themselves will use my weapon and experience pain again ", "Even a capricious child, having known pain, can become an adult.  Pain changes words and thoughts", "You consider yourself the main thing in this world, and you can't even think about your own death.  Because of your world, you have lost the ability to think rationally.  The killers will be killed in return.  The inevitable fate generated by hatred", "Events always occur without warning and only then the reason becomes clear"],
   info: ({
   description: "Yahiko/Pain (弥彦, Yahiko) was a shinobi from Hidden Rain Village. Along with his fellow war orphans, Nagato and Konan (Orphans of Ame), he founded and led Akatsuki in an attempt to bring peace. After Yahiko's death, Nagato  transformed his body into the Deva Path of his Six Paths of Pain, which he used in his public reputation as the new leader of Akatsuki.",
   clan: undefined,
   status: "Dead",
   date: "February 20",
   growth: "Part II: 176.5 cm",
   weight: "Part II: 57.2 kg",
   element: "Water, fire, wind",
   rank: "Rank-S",
   family: undefined
 })
 });

 module.exports = getQuotes;